services:
  - type: web
    name: circuitvision-debugger
    runtime: static
    repo: https://github.com/smile-hart/CircuitVision-Debugger
    branch: main
    staticPublishPath: ./
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
